name: CD for Testing

on:
  push:
    branches:
      - test-env

jobs:
  build_push_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker layer caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV


      # Add image digest for better traceability
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: vhmds/petclinic-test:${{ env.SHORT_SHA }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          provenance: true

      - name: Check repository access
        run: |
          git ls-remote https://github.com/PetClinicby/petclinic-manifests-Testing.git

      - name: Checkout manifests repository
        uses: actions/checkout@v3
        with:
          repository: PetClinicby/petclinic-manifests-Testing
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 1

      - name: Update image tag in deployment manifest
        run: |
          sed -i 's|image: vhmds/petclinic.*|image: vhmds/petclinic-test:'"${{ env.SHORT_SHA }}"'|g' petclinic-deployment.yml

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add petclinic-deployment.yml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
          git push
