name: CD for Dev

on:
  push:
    branches:
      - dev-env

jobs:
  build_push_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        continue-on-error: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        continue-on-error: true
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract short SHA
        id: vars
        continue-on-error: true
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        continue-on-error: true
        run: |
          docker build -t vhmds/petclinic:${{ env.SHORT_SHA }} .
          docker push vhmds/petclinic:${{ env.SHORT_SHA }}
      - name: Check repository access
        continue-on-error: true
        run: |
          git ls-remote https://github.com/PetClinicby/petclinic-manifests-Dev.git

      - name: Checkout manifests repository
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          repository: PetClinicby/petclinic-manifests-Dev
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 1

      - name: Update image tag in deployment manifest
        continue-on-error: true
        run: |
          sed -i 's|image: vhmds/petclinic.*|image: vhmds/petclinic:'"${{ env.SHORT_SHA }}"'|g' petclinic-deployment.yml

      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add petclinic-deployment.yml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
          git push
