name: CI

on:
  pull_request:
    branches:
      - dev-env

jobs:
  build:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Set up Java
        uses: actions/setup-java@v3
        continue-on-error: true
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build and test
        run: mvn clean verify
        continue-on-error: true

      - name: Check code formatting
        run: mvn spotless:check
        continue-on-error: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=PetClinicby_PetClinic
            -Dsonar.organization=Ypetclinicby

