name: CI

on:
  pull_request:
    branches:
      - test-env

jobs:
  build:
    if: github.base_ref == 'test-env' && github.head_ref == 'dev-env'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build and test
        run: |
           mvn clean verify
           mvn test
        continue-on-error: true  # Allow the workflow to continue even if tests fail

      - name: Check code formatting
        run: mvn spotless:check

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=PetClinicby_PetClinic
            -Dsonar.organization=Ypetclinicby

      - name: Run Integration Tests
        run: mvn failsafe:integration-test

      - name: Run Performance Tests
        run: mvn jmeter:jmeter

      - name: OWASP Dependency Check
        run: mvn dependency-check:check

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true

      - name: Build Docker Image
        run: docker build -t petclinic:${{ github.sha }} .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: petclinic:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Save Test Reports
        if: always()  # Run even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            target/surefire-reports/**
            target/failsafe-reports/**
            target/site/jacoco/**
          retention-days: 14

      - name: Save Security Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            target/dependency-check-report.html
            ./**/trivy-results.txt
            target/sonar/**
          retention-days: 14

      - name: Save Performance Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: performance-reports
          path: target/jmeter/results/**
          retention-days: 14

